### ISSUE TITLE
Fix title on social preview

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/laravel-blog#126]
Replace "Laravel 10 blog" to "Laravel blog"

**Comment by krushnarout** [comment]
Hi! May I pick this up?

**Comment by gomzyakov** [comment]
@krushnarout Hello!

Yes, of course) Files with social preview is in folder 'docs'.

**Comment by krushnarout** [comment]
> @krushnarout Hello!
> 
> Yes, of course) Files with social preview is in folder 'docs'.

can you assign it to me :)

**Comment by gomzyakov** [comment]
>can you assign it to me :)

@krushnarout done it)

**Comment by krushnarout** [comment]
> > can you assign it to me :)
> 
> @krushnarout done it)

sorry I thought it a code work, I don't know how to edit photos

**Comment by gomzyakov** [comment]
@krushnarout

> sorry I thought it a code work, I don't know how to edit photos

It's OK)

You can perform another not difficult task, for example https://github.com/gomzyakov/laravel-blog/issues/1
