### ISSUE TITLE
Add the `nunomaduro/phpinsights` package to this app

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/laravel-blog#132]
https://github.com/nunomaduro/phpinsights

**Comment by gagsy** [comment]
Hi,

I have added the phpinsights 

Can i proceed with  pull request or will assign the issue to me

**Comment by gomzyakov** [comment]
__NOTE__: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
