### ISSUE TITLE
Incorrect permissions for users

### ISSUE THREAD

**Issue by michelmelo** [gomzyakov/laravel-blog#175]
Hi, when a user creates a login on the website, they have permission to access the admin.
There should be a lock if you are not an admin, the user cannot have access to create posts, edit and delete.

**Comment by gomzyakov** [comment]
@michelmelo Hello!

Thanks for finding the bug! I or one of the contributors will fix it in the near future.

**Comment by gomzyakov** [comment]
__NOTE__: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
