### ISSUE TITLE
Instructions for non-Docker use?

### ISSUE THREAD

**Issue by circa-0** [gomzyakov/laravel-blog#210]
Wanting to use this on my web server, and uploaded the files. I have composer and tried composer install and it did some stuff, but the artisan command says permission denied. Any help with just installing this on an existing nginx web server VPS?

**Comment by gomzyakov** [comment]
@circa-0 Hello!

I have added instructions for deployment to VDS as part of PR https://github.com/gomzyakov/laravel-blog/pull/230

You can read about the deployment process in file https://github.com/gomzyakov/laravel-blog/blob/main/docs/deploy.md
