### ISSUE TITLE
Translate `README.md` to different languages

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/laravel-blog#221]
Like in project https://github.com/good-first-issues/good-first-issues.github.io

**Comment by gomzyakov** [comment]
@Jetas18 Hello!

You already have experience translating `REDME.md` files into several languages (https://github.com/good-first-issues/good-first-issues.github.io/issues/33).

If you have the desire and time, I can assign this issue to you ;)

**Comment by Jetas18** [comment]
Well I can only translate it to hindi

**Comment by gomzyakov** [comment]
@KrshnK Hello!

Some time ago you translated the `README.md` file into 70+ languages as part of PR https://github.com/good-first-issues/good-first-issues.github.io/pull/77

Do you have the opportunity to make similar translations for this project?

**Comment by KrshnK** [comment]
> @KrshnK Hello!
> 
> Some time ago you translated the `README.md` file into 70+ languages as part of PR [good-first-issues/good-first-issues.github.io#77](https://github.com/good-first-issues/good-first-issues.github.io/pull/77)
> 
> Do you have the opportunity to make similar translations for this project?

@gomzyakov  Sure, I'd be happy to help with translations for your project. Could you provide more details and specify the languages you need? Thanks!
