### ISSUE TITLE
Создай отдельный "маркетинговый" репозиторий `larajournal.github.com`

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/laravel-blog#260]
- Что в нём написать?

**Comment by Daelfresh** [comment]
Hey, how can I fix creating a new post with a 404 | NOT FOUND page

**Comment by gomzyakov** [comment]
__NOTE__: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
