### ISSUE TITLE
Upload `coverage.xml` file to artifacts & upload `coverage.xml` to Codecov in separate CI workflow

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/laravel-blog#265]
- [ ] Upload `coverage.xml` file to artifacts
- [ ] Upload `coverage.xml` to Codecov in separate CI workflow

**Comment by MrRobotIsHere** [comment]
question :Have you ever been worked with laravel backpack cruds package?

**Comment by gomzyakov** [comment]
@MrRobotIsHere No, it didn't work. Would you recommend looking at this package?

**Comment by MrRobotIsHere** [comment]
> @MrRobotIsHere No, it didn't work. Would you recommend looking at this package?

No i just wanted to ask you what's your experience of this pack if you gained.

**Comment by gomzyakov** [comment]
__NOTE__: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
